quarkus:
  application:
    name: afrtn-app
    ui-header: AFRTN Portal
  arc:
    detect-wrong-annotations: true
    remove-unused-beans: false
  http:
    host: localhost
    port: 8181
#  neo4j:
#    uri: bolt://server-address:7687
#    authentication:
#      username: neo4j
#      password: secret
#  vertx:
#    classpath-resolving: false
#    worker-pool-size: 25

"%dev":
  quarkus:
    http:
      host: localhost
      port: 8181

"%test":
  quarkus:
    http:
      host: localhost
      port: 8181
#    neo4j:
#      uri: bolt://server-address:7687
#      authentication:
#        username: neo4j
#        password: secret
#  vertx:
#    classpath-resolving: false
#    worker-pool-size: 25
# Proprietary properties
afrtn.app:
  name=AFRTN Portal

