quarkus:
  arc:
    auto-inject-fields: true
#quarkus.package.type=native
#quarkus.native.additional-build-args=${quarkusNativeArgs}
#quarkus.native.graalvm-home=${quarkus.native.java-home}
#quarkus.native.java-home=${quarkus.native.java-home}
#quarkus.index-dependency.<name>.group-id=
#quarkus.index-dependency.<name>.artifact-id=
#quarkus.index-dependency.<name>.classifier=(this one is optional)
  http:
    host: localhost
    port: 8181
  neo4j:
    uri: bolt://server-address:7687
    authentication:
      username: neo4j
      password: secret
# Portal
afrtn.app:
  name=AFRTN Portal

